USE Proyecto2;
select * from TEMPORAL;

/*PARA INSERTAR AÑOS - 2*/
INSERT INTO FECHA_ELECCION(anoEleccion)
SELECT DISTINCT AÑO_ELECCION FROM TEMPORAL;

/*PARA INSERTAR ELECCION - 1*/
INSERT INTO ELECCION(nombre)
SELECT DISTINCT NOMBRE_ELECCION FROM TEMPORAL;

/*PARA INSERTAR RAZA - 3*/
INSERT INTO RAZA(descripcion)
SELECT DISTINCT RAZA FROM TEMPORAL;

/*PARA INSERTAR SEXO - 2*/
INSERT INTO SEXO(descripcion)
SELECT DISTINCT SEXO FROM TEMPORAL;

/*PARA INSERTAR PARTIDO - 18*/
INSERT INTO PARTIDO(abreviacion,nombre)
SELECT DISTINCT PARTIDO,NOMBRE_PARTIDO FROM TEMPORAL;

/*PARA INSERTAR PAIS - 6*/
INSERT INTO PAIS(nombre) 
SELECT DISTINCT PAIS FROM TEMPORAL;

/*PARA INSERTAR REGION - 22*/
SELECT count(*) FROM REGION;
INSERT INTO REGION(nombre,idPais)
SELECT DISTINCT REGION,PAIS.idPais FROM TEMPORAL
INNER JOIN PAIS ON PAIS.nombre = TEMPORAL.pais;

/*PARA INSERTAR DEPARTAMENTO - 81*/
INSERT INTO DEPARTAMENTO (nombre,idRegion)
SELECT DISTINCT DEPTO,REGION.idRegion FROM TEMPORAL
INNER JOIN REGION ON TEMPORAL.REGION = REGION.nombre
INNER JOIN PAIS ON REGION.idPais = PAIS.idPais AND TEMPORAL.PAIS = PAIS.nombre;

/*PARA INSERTAR MUNICIPIO - 1,169*/
INSERT INTO MUNICIPIO (nombre,idDepartamento)
SELECT DISTINCT TEMPORAL.MUNICIPIO,DEPARTAMENTO.idDepartamento FROM TEMPORAL
INNER JOIN DEPARTAMENTO ON TEMPORAL.DEPTO = DEPARTAMENTO.nombre
INNER JOIN REGION ON TEMPORAL.REGION = REGION.nombre AND REGION.idRegion = DEPARTAMENTO.idRegion
INNER JOIN PAIS ON TEMPORAL.PAIS = PAIS.nombre AND REGION.idPais = PAIS.idPais;


/*PARA INSERTAR EN DETALLE_ELECCION - 20970*/
INSERT INTO DETALLE_ELECCION (analfabetos,alfabetos,primaria,nivel_medio,universitario,idPartido,idRaza,idSexo,idMunicipio,idFechaEleccion,idEleccion)
SELECT DISTINCT TEMPORAL.ANALFABETOS,TEMPORAL.ALFABETOS,TEMPORAL.PRIMARIA,TEMPORAL.NIVEL_MEDIO,TEMPORAL.UNIVERSITARIOS,
PARTIDO.idPartido,RAZA.idRaza,SEXO.idSexo,MUNICIPIO.idMunicipio,FECHA_ELECCION.idFechaEleccion,ELECCION.idEleccion FROM TEMPORAL
INNER JOIN PARTIDO ON TEMPORAL.PARTIDO = PARTIDO.abreviacion
INNER JOIN RAZA ON TEMPORAL.RAZA = RAZA.descripcion
INNER JOIN SEXO ON TEMPORAL.SEXO = SEXO.descripcion
INNER JOIN MUNICIPIO ON  TEMPORAL.MUNICIPIO = MUNICIPIO.nombre
INNER JOIN DEPARTAMENTO ON TEMPORAL.DEPTO = DEPARTAMENTO.nombre AND MUNICIPIO.idDepartamento = DEPARTAMENTO.idDepartamento
INNER JOIN REGION ON TEMPORAL.REGION = REGION.nombre AND REGION.idRegion = DEPARTAMENTO.idRegion
INNER JOIN PAIS ON TEMPORAL.PAIS = PAIS.nombre AND REGION.idPais = PAIS.idPais
INNER JOIN FECHA_ELECCION ON TEMPORAL.AÑO_ELECCION = FECHA_ELECCION.anoEleccion
INNER JOIN ELECCION ON TEMPORAL.NOMBRE_ELECCION = ELECCION.nombre
;
